name: "Distribute upload"
description: "Uploads the package from the dist dir to GitHub artifacts or Google Drive"
inputs:
  use-github:
    description: "Whether to upload to GitHub artifacts"
    required: true

  use-aws-s3:
    description: "Whether to upload to AWS S3"
    required: true

  github-target-filename:
    description: "Target filename in GitHub artifacts"
    required: true

  aws-s3-target-dir:
    description: "Target directory in AWS S3"
    default: "synergy-1"
    required: true

  aws-s3-package-version:
    description: "Package version to use in the AWS S3 path"
    required: true

  aws-access-key-id:
    description: "AWS access key ID"
    required: true
  
  aws-secret-access-key:
    description: "AWS secret access key"
    required: true

  aws-region:
    description: "AWS region"
    default: "us-east-2"
    required: true

  aws-s3-bucket:
    description: "AWS S3 bucket name"
    default: muskoka-packages
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        if [[ "${{ inputs.use-github }}" == 'true' && "${{ inputs.use-aws-s3 }}" == 'true' ]]; then
          echo "Either 'use-github' or 'use-aws-s3' must be true (and not both)"
          exit 1
        fi

        if [[ "${{ inputs.use-github }}" == 'false' && "${{ inputs.use-aws-s3 }}" == 'false' ]]; then
          echo "Either 'use-github' or 'use-aws-s3' must be true"
          exit 1
        fi

        if [[ "${{ inputs.use-aws-s3 }}" == 'true' ]]; then
          if [[ -z "${{ inputs.aws-s3-target-dir }}" ]]; then
            echo "Input 'aws-s3-target-dir' is required when uploading to AWS S3"
            exit 1
          fi
          if [[ -z "${{ inputs.aws-access-key-id }}" ]]; then
            echo "Input 'aws-access-key-id' is required when uploading to AWS S3"
            exit 1
          fi
          if [[ -z "${{ inputs.aws-secret-access-key }}" ]]; then
            echo "Input 'aws-secret-access-key' is required when uploading to AWS S3"
            exit 1
          fi
          if [[ -z "${{ inputs.aws-region }}" ]]; then
            echo "Input 'aws-region' is required when uploading to AWS S3"
            exit 1
          fi
          if [[ -z "${{ inputs.aws-s3-package-version }}" ]]; then
            echo "Input 'aws-s3-package-version' is required when uploading to Google Drive"
            exit 1
          fi
        fi
      shell: bash

    - name: Upload to GitHub
      if: ${{ inputs.use-github == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.github-target-filename }}
        path: ./dist
    
    - name: AWS credentials
      if: ${{ inputs.use-aws-s3 == 'true' }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Upload to AWS S3
      if: ${{ inputs.use-aws-s3 == 'true' }}
      run: |
        source_dir="./dist/"

        # Should be the product name
        base_dir="${{ inputs.aws-s3-target-dir }}"

        # Separate snapshot and release versions for easier navigation
        if [[ "${{ inputs.aws-s3-package-version }}" =~ snapshot ]]; then
          sub_dir="snapshot"
        else
          sub_dir="release"
        fi

        # Organize by major.minor.patch dir (i.e. v1.0.0/v1.0.0-foobar+r123)
        short_version=$(echo "${{ inputs.aws-s3-package-version }}" | cut -d'-' -f1 | cut -d'+' -f1)

        target_dir="$base_dir/$sub_dir/$short_version/${{ inputs.aws-s3-package-version }}"
        url="s3://${{ inputs.aws-s3-bucket }}/$target_dir"

        echo "Uploading to AWS S3: $url"
        aws s3 cp $source_dir $url

        if [[ $? -ne 0 ]]; then
          echo "Failed to upload to AWS S3" >&2
          exit 1
        fi

      shell: bash
