name: "Distribute upload"
description: "Uploads the package from the dist dir to GitHub artifacts or Google Drive"
inputs:
  use-github:
    description: "Whether to upload to GitHub artifacts"
    required: true

  use-gdrive:
    description: "Whether to upload to Google Drive"
    required: true

  github-target-filename:
    description: "Filename to upload (GitHub artifacts)"
    required: true

  gdrive-target-base-dir:
    description: "Base directory to upload (Google Drive)"
    required: true

  gdrive-secret-key:
    description: "Google Drive secret key"
    required: true

  gdrive-parent-folder-id:
    description: "Google Drive parent folder ID"
    required: true

  package-version:
    description: "Package version appended to the Google Drive dir"
    required: true

runs:
  using: "composite"

  steps:
    - run: |
        if [[ "${{ inputs.use-github }}" == 'true' && "${{ inputs.use-gdrive }}" == 'true' ]]; then
          echo "Either 'use-github' or 'use-gdrive' must be true (and not both)"
          exit 1
        fi
        if [[ "${{ inputs.use-github }}" == 'false' && "${{ inputs.use-gdrive }}" == 'false' ]]; then
          echo "Either 'use-github' or 'use-gdrive' must be true"
          exit 1
        fi
        if [[ "${{ inputs.use-gdrive }}" == 'true' ]]; then
          if [[ -z "${{ inputs.package-version }}" ]]; then
            echo "Input 'package-version' is required when uploading to Google Drive"
            exit 1
          fi
          if [[ -z "${{ inputs.gdrive-target-base-dir }}" ]]; then
            echo "Input 'gdrive-target-base-dir' is required when uploading to Google Drive"
            exit 1
          fi
          if [[ -z "${{ inputs.gdrive-secret-key }}" ]]; then
            echo "Input 'gdrive-secret-key' is required when uploading to Google Drive"
            exit 1
          fi
          if [[ -z "${{ inputs.gdrive-parent-folder-id }}" ]]; then
            echo "Input 'gdrive-parent-folder-id' is required when uploading to Google Drive"
            exit 1
          fi
        fi
      shell: bash

    - name: Upload to GitHub
      if: ${{ inputs.use-github == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.github-target-filename }}
        path: ./dist

    - name: Google Drive vars
      id: google-drive
      if: ${{ inputs.use-gdrive == 'true' }}
      shell: bash
      run: |
        # Remove stage (pre-release version) and version metadata (has build number)
        short_version=$(echo "${{ inputs.package-version }}" | cut -d'-' -f1 | cut -d'+' -f1)

        if [[ "${{ inputs.package-version }}" =~ snapshot ]]; then
          sub_dir="snapshot"
        else
          sub_dir="release"
        fi

        base_dir="${{ inputs.gdrive-target-base-dir }}"
        dir="Packages/$base_dir/$short_version/$sub_dir/${{ inputs.package-version }}"
        echo "dir=$dir" | tee -a $GITHUB_OUTPUT

    - name: Upload to Google Drive
      if: ${{ inputs.use-gdrive == 'true' }}
      uses: symless/gdrive-upload@target-glob
      with:
        credentials: ${{ inputs.gdrive-secret-key }}
        target: "./dist/*"
        parent_folder_id: ${{ inputs.gdrive-parent-folder-id }}
        child_folder: ${{ steps.google-drive.outputs.dir }}
